# -*- coding: utf-8 -*-
"""seasons.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Hkiz5TEoJYgsmqcSSDunVQ54saFgmYp
"""

from datetime import date
import re
import sys
import inflect 

p = inflect.engine()

def main():
    birth_date = input("Date of Birth: ")
    try:
      year, month, day = check_birthday(birth_date)

    except:
      sys.exit("Invalid Date")
    date_of_birth = date(int(year), int(month),int(day))
    date_of_today = date.today()
    diff=date_of_today -  date_of_birth
    total_minutes = diff.days * 24 * 60
    output = p.number_to_words(total_minutes, andword="")
    #print(date_of_birth)
    #print(date_of_today)
    print(total_minutes)
    #print(diff.days)
    print(output.capitalize()+ " minutes")

def check_birthday(birth_date):
  if re.search(r"^[0-9]{4}-[0-9]{2}-[0-9]{2}$",birth_date):
    year,month,day = birth_date.split("-")
    return year, month, day

      
    
if __name__ == "__main__":
    main()